//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalResidential_Web.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class appusers
    {
        public int id { get; set; }
        public Nullable<long> id_address { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string contrasena { get; set; }
        public System.DateTime reg_date { get; set; }
    
        public virtual defaultaddress defaultaddress { get; set; }
    }
}
