//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalResidential_Web.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class defaultaddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public defaultaddress()
        {
            this.appusers = new HashSet<appusers>();
        }
    
        public long id { get; set; }
        public string address { get; set; }
        public bool isavailable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appusers> appusers { get; set; }
    }
}
